# Generated by Django 2.2 on 2020-09-17 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartype',
            old_name='useful_lenght',
            new_name='useful_length',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='lenght',
            new_name='length',
        ),
    ]
