# Generated by Django 2.2 on 2020-09-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0003_auto_20200917_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('p', 'petrol'), ('d', 'diesel'), ('g', 'gas')], default='p', max_length=1),
        ),
        migrations.DeleteModel(
            name='Fuel',
        ),
    ]
