# Generated by Django 2.2 on 2020-09-21 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0006_auto_20200921_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairticket',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broken_cars', related_query_name='broken_car', to='garage_app.Car', verbose_name='машина'),
        ),
    ]
