# Generated by Django 2.2 on 2020-09-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0011_auto_20200924_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairticket',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='ремонт окончен'),
        ),
    ]
